[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
license = "MIT"
publish = false

[workspace.dependencies]
libclankerd = { path = "crates/libclankerd" }
clankerd-proto = { path = "crates/clankerd-proto" }
libkrun-sys = { path = "crates/libkrun-sys" }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
